# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBtZt5fmzNdKueeKKAfveaZnjHQqLRIr
"""

# Get the sentimet of text from website

pip install newspaper3k

#Import the libraries
from textblob import TextBlob
import nltk
from newspaper import Article

# Get the article
url = 'https://active.ai/'
article = Article(url)

# Do some NLP
article.download()
article.parse()
nltk.download('punkt')
article.nlp()

# Get the summary of the article
text = article.summary

#print the text
print(text)

# Create a textblob object
obj = TextBlob(text)

# This returns a value between -1 and 1
sentiment = obj.sentiment.polarity
print(sentiment)

if sentiment == 0:
  print('The text is Neutral')
elif sentiment > 0:
  print('The text is Positive')
else:
  print('The text is Negative')